# Generated by Django 5.2.8 on 2025-11-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartPage', '0002_alter_cartitem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='size',
            field=models.CharField(default='Medium', max_length=20),
        ),
    ]
